######################################
#### manual configuration example: ###
#Twitter:
#  access_token: XXX-XXX
#  access_token_secret: XXX
#  consumer_key: XXX
#  consumer_secret: XXX
#
#Discord:
#  - IncludeReplyToUser: false
#    IncludeRetweet: false
#    IncludeUserReply: true
#    custom_message: 'A new tweet!'
#    keyword_sets:
#    - - 'League'    # tweet will be posted if tweet contains all 3 words {League of Legends}, no particular order.
#      - 'of'
#      - 'Legends'
#    - - 'Dota 2'    # tweet will be posted if tweet contains 'Dota 2' in this specific order
#    - - 'MOBA'      # tweet will be posted if it contains 'MOBA'
#    twitter_ids:
#    - '123'         # define as many as you want with a dash {-} at the beginning
#    - '456'
#    twitter_handles:
#    - 'discordapp'
#    twitter_lists:
#    - 'https://twitter.com/rokxx/lists/dota-2'
#    webhook_urls:
#    - 'https://discordapp.com/api/webhooks/123456/XXXX-XXXX'
######################################

# configuration through environment variables
Twitter:
  access_token: ${ACCESS_TOKEN}
  access_token_secret: ${ACCESS_TOKEN_SECRET}
  consumer_key: ${CONSUMER_KEY}
  consumer_secret: ${CONSUMER_SECRET}

Discord:
  - IncludeReplyToUser: true
    IncludeRetweet: true
    IncludeUserReply: true
    IncludeAttachment: true
    IncludeQuote: true
    CreateEmbed: true
    twitter_handles: ['MiraculousMX']
    webhook_urls: ['https://discord.com/api/webhooks/920738938228981883/F3ijKXf0CRIBsychyjS-HhCyA8Z9tg0mZp1ZwtRVytl2maoyql-b-m0Zk9CpWRN0m5bD']

  - IncludeReplyToUser: true
    IncludeRetweet: true
    IncludeUserReply: true
    IncludeAttachment: true
    IncludeQuote: true
    CreateEmbed: true
    twitter_handles: ['ladyofacat']
    webhook_urls: ['https://discord.com/api/webhooks/920739522004807730/Ih85c-FK_81z_CMULSkUzye8uLMlQI7UYGAyP2fJs0__CM7tA7iAM_UwKFg_CVu726MC']

  - IncludeReplyToUser: true
    IncludeRetweet: true
    IncludeUserReply: true
    IncludeAttachment: true
    IncludeQuote: true
    CreateEmbed: true
    twitter_handles: ['Thomas_Astruc', 'zsotroav']
    webhook_urls: ['https://discord.com/api/webhooks/920739945553993800/PocZNhAK98cTvrSNcFQ1IfJzlOcGF8IUcJJawctoaWnCbGUBc3tLfxdv2abhLPUQo3e6']
